# Le nom exact qui correspond au fichier du Config Server
spring.application.name=delivery-service

# Force l'activation du client Config
spring.cloud.config.enabled=true

# Lien direct pour importer la configuration depuis le port 8888
spring.config.import=optional:configserver:http://localhost:8888

# Exposer publiquement l'endpoint de santé
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always